### ISSUE TITLE
paper

### ISSUE THREAD

**Issue by takiee** [deyingk/PersonalizedHandMeshEstimation#2]
Interesting work！Congras for ECCV2022!
When will you release the paper? Can't wait to see it.

**Comment by zhanpengxin** [comment]
你好，我已收到你的邮件，我会及时处理^_^

**Comment by kfzyqin** [comment]
Can you please also send me a paper? Thank you very much :-)

**Comment by deyingk** [comment]
The paper link is up now :-) 
Sorry for the late reply and thanks for your patience!
